"""fix hash data in document table

Revision ID: 360c65a62392
Revises: 8d6986c58f09
Create Date: 2024-11-15 17:16:48.117093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '360c65a62392'
down_revision: Union[str, None] = '8d6986c58f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('hash_data', sa.String(), nullable=True))
    op.drop_constraint('documents_hash_key', 'documents', type_='unique')
    op.create_unique_constraint(None, 'documents', ['hash_data'])
    op.drop_column('documents', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('hash', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_unique_constraint('documents_hash_key', 'documents', ['hash'])
    op.drop_column('documents', 'hash_data')
    # ### end Alembic commands ###
