"""Link work_id at document table

Revision ID: 8d6986c58f09
Revises: b386f06edbd8
Create Date: 2024-11-13 18:00:01.069089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6986c58f09'
down_revision: Union[str, None] = 'b386f06edbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('work_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'work_id')
    # ### end Alembic commands ###
