"""Initial migration

Revision ID: b386f06edbd8
Revises: 
Create Date: 2024-11-13 17:57:38.920195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b386f06edbd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('compute', sa.Text(), nullable=True),
    sa.Column('personnel', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('s3uri', sa.Text(), nullable=False),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('initial_document_id', sa.Integer(), nullable=False),
    sa.Column('primary_document_id', sa.Integer(), nullable=False),
    sa.Column('provenance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initial_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['primary_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('documents')
    op.drop_table('provenance')
    # ### end Alembic commands ###
